### PR TITLE
Configure factory to deploy EIP-1167 minimal proxies

### PR DESCRIPTION
**Pull request by mds1**
Updates the PToken Factory contract to use EIP-1167 minimal proxies to reduce gas costs. Gas costs decrease from 2.15M ($37) to 315k ($5) as a result.

The second commit just adds Prettier and Solhint to lint and format the code, and applies their changes. To really see the changes, it may be easier to look at the diff of the first commit [here](https://github.com/raid-guild/gitcoinco-ptoken-contracts/pull/2/commits/e807893c7927090dbd216bce0a6d4d787353023f).

Here is a brief overview and explanation of those changes, walking down the file list in the order shown in that diff:
- In `PToken.sol`, we now use `@openzeppelin/contracts-ethereum-package` instead of `@openzeppelin/contracts`. 
    - These are the same packages, but the former is a fork that supports upgradable contracts. We do not have upgradable contracts here, but this is still required because, like upgradable contracts, minimal proxy deployments cannot rely on a constructor.
    - As a result, contracts have a special initializer function that must be called manually and can only be called once. Initializer functions of contracts you inherit from must also be called manually

- In the constructor of `PTokenFactory.sol`, we deploy one instance of `PToken.sol` which acts as the logic template that all PToken contracts will delegatecall too. We initialize it with some dummy data to ensure no one can use this contract.

- In the `createPToken` function we call `deployMinimal` to deploy the minimal proxy, and encode the call to the initialization function. This lets us call it in the same transaction and prevents frontrunning.

- See the comments in `ProxyFactory.sol` for an explanation of that contract.

- In `ptoken.spec.js`, we add a check that the logic template was properly deployed. Aside from that, all functionality is the same

### CODE REVIEW

**Comment by apbendi** [comment]
They proxy setup looks great @mds1, nice work on that! Don't see any issues.

One non-proxy related note is call to `transferFrom` in the token purchase method, https://github.com/raid-guild/gitcoinco-ptoken-contracts/pull/2/commits/e807893c7927090dbd216bce0a6d4d787353023f#diff-a33ca4e6045d4c00783a86464bcdf903R46

I think we should either be checking requiring the return value is `true`, or better yet, using `SafeERC20` from OZ. Am I missing something there?

**Comment by mds1** [comment]
Good call! None of the return values were being checked. So in the last commit I:
- Added checks on return value
- Ran `slither-check-erc contracts/PToken.sol PToken` to confirm conformance to ERC20 standard
- Removed the old `@openzeppelin/contracts` package since we no longer need it

The tests are lacking a bit, so in a separate PR we might want to write a few adversarial tests and make sure nothing breaks

**Comment by apbendi** [comment]
@mds1 is the accepted token configurable by the user? If so, we should probably consider SafeERC20 here. Tether would be the number one offender to worry about in this regard— their implementation does not return a bool.

**Comment by mds1** [comment]
I believe the frontend hardcodes it as Dai for now, but yes it is configurable. We are using `safeTransferFrom` in the last commit as seen here: https://github.com/raid-guild/gitcoinco-ptoken-contracts/pull/2/commits/99106119ef18c9a7aeae0d5f2c6877228ed41d06#diff-a33ca4e6045d4c00783a86464bcdf903R48

**Comment by apbendi** [comment]
Ahh sorry @mds1 missed that you had already included that change 👍

**Comment by mds1** [comment]
@proofoftom I think this is good to merge then unless you have any questions!

**Comment by mds1** [comment]
Hey @proofoftom and @apbendi this is ready for final review + merge! Just added two commits for you to review

**Pull request merged**
